"""drift_checks: nullable window stats for cold-start rows

Revision ID: 1c2bac665aed
Revises: 45ced6ccd6ca
Create Date: 2026-08-13 01:09:48.962148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2bac665aed'
down_revision: Union[str, Sequence[str], None] = '45ced6ccd6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drift_checks', 'window_mean',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    op.alter_column('drift_checks', 'window_stdev',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    op.alter_column('drift_checks', 'delta',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    op.alter_column('drift_checks', 'z_score',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drift_checks', 'z_score',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    op.alter_column('drift_checks', 'delta',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    op.alter_column('drift_checks', 'window_stdev',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    op.alter_column('drift_checks', 'window_mean',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               nullable=False)
    # ### end Alembic commands ###
