"""widen cost precision

Revision ID: 45ced6ccd6ca
Revises: 6003c268b4bf
Create Date: 2026-08-12 02:12:28.542185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ced6ccd6ca'
down_revision: Union[str, Sequence[str], None] = '6003c268b4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'cost_usd',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.Numeric(precision=14, scale=10),
               existing_nullable=True)
    op.alter_column('runs', 'total_cost_usd',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               type_=sa.Numeric(precision=14, scale=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'total_cost_usd',
               existing_type=sa.Numeric(precision=14, scale=10),
               type_=sa.NUMERIC(precision=12, scale=6),
               existing_nullable=False)
    op.alter_column('results', 'cost_usd',
               existing_type=sa.Numeric(precision=14, scale=10),
               type_=sa.NUMERIC(precision=12, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###
