"""add index on drift_checks (model_id, category, created_at desc)

Revision ID: dd46d7592b6f
Revises: 1c2bac665aed
Create Date: 2026-08-13 01:58:55.755555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd46d7592b6f'
down_revision: Union[str, Sequence[str], None] = '1c2bac665aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_drift_checks_model_category_created_at', 'drift_checks', ['model_id', 'category', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_drift_checks_model_category_created_at', table_name='drift_checks')
    # ### end Alembic commands ###
